############################
## Hugo Site Configuration
## LoveIt Theme
############################

baseURL: 'https://kepa.eu.org/'
title: 'kepa.eu.org'

############################
## MISC
############################

enableEmoji: true
enableRobotsTXT: true
enableGitInfo: true
languageCode: 'en'
languageName: 'English'
hasCJKLanguage: false
timeZone: Etc/UTC

# Copyright for SEO schema
copyright: '© 2024-2026 Mati Kepa'

# Ignore some build errors
ignoreErrors:
  - error-remote-getjson
  - error-missing-instagram-accesstoken

# Pagination
pagination:
  pagerSize: 10

# Sitemap
sitemap:
  filename: sitemap.xml
  changefreq: weekly
  priority: 0.5

# Permalinks
permalinks:
  blog: ':contentbasename'

# Markup
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6

# Media types for markdown output
mediaTypes:
  text/plain:
    suffixes:
      - md

# Output formats
outputFormats:
  MarkDown:
    mediaType: text/plain
    isPlainText: true
    isHTML: false

# Outputs - JSON needed for LoveIt search
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - MarkDown
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
