############################
## CHANGE THESE
############################

baseURL: "https://kepa.eu.org/"
title: "kepa.eu.org"

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-US"
timeZone: Etc/UTC

## This part is being overwritten by the manually created file
# enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: true

sitemap:
  filename: sitemap.xml
  changefreq: monthly
  priority: 0.6

security:
  allow_frame: false
  csp:
    policy: ""
    report_only: false
