############################
## Author
############################

author:
  name: 'Mateusz (Mati) Kępa'
  image: author.jpeg
  greeting: 'Hello there and welcome to my personal blog page! :hugs:'
  icon: ':wave:'

############################
## Links
############################

links:
  - github: https://github.com/matikepa/matsonkepson.github.io
  # - gitlab:
  # - facebook:
  # - x-twitter:
  # - mastodon:
  - linkedin: https://linkedin.com/in/matikepa/
  # - instagram:
  # - reddit:
  # - telegram:
  # - whatsapp:
  # - signal:
  # - codepen:
  # - dev:
  - email: mailto:devnull@kepa.eu.org?subject=Contact%20from%20website%20link%20kepa.eu.org&body=Your%20message%20goes%20here...
  # - website:
  # - link:
  # - discord:
  # - orcid:
  # - slack:
  - stack-overflow: https://stackoverflow.com/users/7786358/
  # - twitch:
  # - patreon:
  # - soundcloud:
  # - dribbble:
  # - stack-exchange:
  # - tiktok:
  # - youtube:
  # - keybase:
  # - flickr:
  # - tumblr:
  # - kickstarter:
  # - snapchat:
  # - bluesky:
  # - bitbucket:
  # - bandcamp:
  # - etsy:
  # - spotify:
  # - pinterest:
  # - strava:
  # - untappd:
  # - skype:
  # - medium:
  # - foursquare:
  # - apple:
  # - amazon:
  # - google:
  # - paypal:
  # - pgp-key:
  # - windows:
  # - codeberg:
  # - pixelfed:
  # - substack:
  # - newsletter: https://kepa.eu.org/blog/
  - newsletter: /index.xml

###############################
## OpenGraph & Twitter Cards
###############################

title: 'Mati Kepa'
description: 'Build with Qubt & Hugo & GitHub Pages'
images:
  - author.jpeg

###############################
## Latex math
###############################

# To configure Latex rendering on all pages, change to: true
#
# To only add Latex rendering on pages that need it, set in the frontmatter
# of each page that needs it:
#   params:
#     math: true
# This option will allow better performance, as it'll only load
# the extra JS when needed.
math: false
