version: 2
updates:
  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'dependabot github-actions'
    labels:
      - 'dependencies'
      - 'ci'
      - 'shell-scripts'

  # Hugo dependencies
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'dependabot gomod'
    labels:
      - 'dependencies'
      - 'hugo'

  # Python dependencies
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'dependabot pip'
    labels:
      - 'dependencies'
      - 'python'
