version: 2
updates:
  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'ci'
      - 'shell-scripts'

  # Hugo dependencies
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'hugo'

  # Python dependencies
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'python'

  # Pre-commit hooks
  - package-ecosystem: 'pip'
    directory: '/.pre-commit-config.yaml'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'pre-commit'
