repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Updated from v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: end-of-file-fixer

  # - repo: https://github.com/DavidAnson/markdownlint
  #   rev: v0.31.1
  #   hooks:
  #     - id: markdownlint
  #       additional_dependencies: [markdownlint-cli]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: \.(md|markdown|yaml|yml|json|js|ts|css|scss)$
        exclude: ^vendor/
