# .github/workflows/analytics.yml
name: Page Analytics
on:
  schedule:
    - cron: '0 0 * * *' # Daily analytics update

jobs:
  analytics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch GitHub Pages Analytics
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/pages/traffic
