name: Page Analytics
on:
  schedule:
    - cron: '0 0 * * *' # Daily analytics update
  workflow_dispatch:     # Manual trigger option

jobs:
  analytics:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: read
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive.key | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: Fetch GitHub Pages Analytics
        run: |
          echo "Fetching GitHub Pages analytics..."
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/pages/traffic \
            --jq '.' > analytics-$(date +%Y-%m-%d).json

          echo "Analytics data saved to analytics-$(date +%Y-%m-%d).json"
          cat analytics-$(date +%Y-%m-%d).json
