name: Page Analytics
on:
  schedule:
    - cron: '0 0 * * *' # Daily analytics update
  workflow_dispatch: # Manual trigger option

jobs:
  analytics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: read
    env:
      GH_TOKEN: ${{ secrets.ANALYTICS_TOKEN }}
    steps:
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl wget -y)
          sudo apt update
          sudo apt install gh jq -y
      - uses: actions/checkout@v4
      - name: Fetch Repository Analytics
        run: |
          echo "Fetching repository analytics..."
          DATE=$(date +%Y-%m-%d)

          # Check if token is available
          if [ -z "$GH_TOKEN" ]; then
            echo "Error: ANALYTICS_TOKEN secret is not set."
            echo "Please create a Personal Access Token with 'repo' scope and add it as ANALYTICS_TOKEN secret."
            exit 1
          fi
          # Create analytics directory
          mkdir -p analytics

          # Function to make API calls with better error handling
          fetch_analytics() {
            local endpoint="$1"
            local output_file="$2"
            local description="$3"
            echo "Fetching $description..."
            if gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "/repos/${{ github.repository }}/$endpoint" \
              --jq '.' | jq > "$output_file" 2>/dev/null; then
              echo "✓ Successfully fetched $description"
            else
              echo "✗ Failed to fetch $description (this may be normal if no data is available)"
              echo '{"error": "No data available or insufficient permissions"}' > "$output_file"
            fi
          }

          # Fetch different types of analytics
          fetch_analytics "traffic/views" "analytics/page-views-${DATE}.json" "page views"
          fetch_analytics "traffic/clones" "analytics/clones-${DATE}.json" "repository clones"
          fetch_analytics "traffic/popular/paths" "analytics/referral-paths-${DATE}.json" "top referral paths"
          fetch_analytics "traffic/popular/referrers" "analytics/referral-sources-${DATE}.json" "top referral sources"

          echo "Analytics data saved for ${DATE}"
          ls -la analytics/
          # Display summary
          echo "=== Analytics Summary for ${DATE} ==="
          if [ -f "analytics/page-views-${DATE}.json" ] && ! grep -q "error" "analytics/page-views-${DATE}.json"; then
            echo "Page Views:"
            cat analytics/page-views-${DATE}.json | jq -r '"Total views: \(.count // "N/A"), Unique visitors: \(.uniques // "N/A")"'
          else
            echo "Page Views: No data available"
          fi
          if [ -f "analytics/clones-${DATE}.json" ] && ! grep -q "error" "analytics/clones-${DATE}.json"; then
            echo "Repository Clones:"
            cat analytics/clones-${DATE}.json | jq -r '"Total clones: \(.count // "N/A"), Unique cloners: \(.uniques // "N/A")"'
          else
            echo "Repository Clones: No data available"
          fi

      - name: Commit Analytics Data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add analytics/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add analytics data for $(date +%Y-%m-%d)"
            git push
          fi
