name: Automatic PR creation
on:
  push:
    branches:
      - develop
jobs:
  createPullRequestforMain:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Get latest changes
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.PR_TOKEN }}
          commit-message: Update main
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: develop
          title: 'Update develop to main'
          labels: |
            update
          assignees: matsonkepson
          draft: false
